import { ThemeType, StylesType } from './types';

export const ThemeStyles: Record<ThemeType, StylesType> = {
	[ThemeType.Default]: {
		backgroundsMess: '#f7f9fa',
		backgroundsHeaderMess: '#f8f9fb',
		colorTextChat: '#000',
		messContainerBackground: '#ebebeb',
		myMessContainerBackground: '#007aff',
		inputBackground: '#ebebeb',
		inputPlaceholderColor: '#000',
		inputTextColor: '#000',
		buttonColorCircle: '#007aff',
		buttonColorIcon: '#fff',
		selectChatBackground: '#4169E1',
		searchColor: '#6495ED',
		headerUnderline: '3px solid #f1f3f4',
	},
	[ThemeType.Night]: {
		backgroundsMess: '#0E1621',
		backgroundsHeaderMess: '#17212B ',
		colorTextChat: '#fff',
		messContainerBackground: '#182533',
		myMessContainerBackground: '#2B5278',
		inputBackground: '#17212B ',
		inputPlaceholderColor: '#58646F',
		inputTextColor: '#fff',
		buttonColorCircle: '#5288C1',
		buttonColorIcon: '#17212B ',
		selectChatBackground: '#17212B ',
		searchColor: '#242F3D',
		headerUnderline: '#242F3D',
	},
	[ThemeType.Green]: {
		backgroundsMess: '#f7f9fa',
		backgroundsHeaderMess: '#f8f9fb',
		colorTextChat: '#000',
		messContainerBackground: '#ebebeb',
		myMessContainerBackground: '#008069',
		inputBackground: '#ebebeb',
		inputPlaceholderColor: '#000',
		inputTextColor: '#000',
		buttonColorCircle: '#008069',
		buttonColorIcon: '#fff',
		selectChatBackground: '#008069',
		searchColor: '#019d81',
		headerUnderline: '3px solid #f1f3f4',
	},
};
