name: prod Push Action

on:
  push:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: Install modules
        run: npm install
      - name: Build Storybook
        run: npm run build-storybook
      - name: Firebase Deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          sudo npm install -g firebase-tools
          firebase use prod
          firebase deploy --only hosting:prod
